### ISSUE TITLE
Instructions of deploying on Taubyte

### ISSUE THREAD

**Issue by v1rtl** [samyfodil/taubyte-llama-satellite#1]
Would be cool to have a instruction in readme how to deploy this project on tau (w/ `tau` CLI)

**Comment by samyfodil** [comment]
README updated. please refer to it for build.
to deploy you just need to drop the binary in /tb/plugins 
if you'd like to test locally with dreamland check README of https://github.com/taubyte/vm-orbit

**Comment by samyfodil** [comment]
@gedw99 it was moved to tau -> https://github.com/taubyte/tau/tree/main/pkg/vm-orbit
